// Auto-generated sprite definitions
// This file is generated by SGDK's resource compiler
#ifndef _SPRITE_H_
#define _SPRITE_H_

#include <genesis.h>

// Include stubs for compilation testing
#include "sprite_stubs.h"

#endif
