// Stub sprite definitions for compilation testing
// In a real build, these would be generated by SGDK's resource compiler

#ifndef _SPRITE_STUBS_H_
#define _SPRITE_STUBS_H_

#include <genesis.h>

// Stub sprite definitions - these would normally be generated
extern const SpriteDefinition spr_point;
extern const SpriteDefinition spr_ryo_100;
extern const SpriteDefinition spr_ryo_101;
extern const SpriteDefinition spr_ryo_102;
extern const SpriteDefinition spr_ryo_103;
extern const SpriteDefinition spr_ryo_104;
extern const SpriteDefinition spr_ryo_105;
extern const SpriteDefinition spr_ryo_106;
extern const SpriteDefinition spr_ryo_107;
extern const SpriteDefinition spr_ryo_108;
extern const SpriteDefinition spr_ryo_113;
extern const SpriteDefinition spr_ryo_151;
extern const SpriteDefinition spr_ryo_152;
extern const SpriteDefinition spr_ryo_154;
extern const SpriteDefinition spr_ryo_155;
extern const SpriteDefinition spr_ryo_200;
extern const SpriteDefinition spr_ryo_201;
extern const SpriteDefinition spr_ryo_202;
extern const SpriteDefinition spr_ryo_204;
extern const SpriteDefinition spr_ryo_205;
extern const SpriteDefinition spr_ryo_207;
extern const SpriteDefinition spr_ryo_208;
extern const SpriteDefinition spr_rect_bb;
extern const SpriteDefinition spr_rect_hb;

// Stub palette definitions
extern const Palette spr_ryo_pal1;
extern const Palette spr_ryo_pal2;

// Stub image definitions
extern const Image room_0_bgb;
extern const Image room_0_bga;
extern const Image gfx_bgb1;
extern const Image gfx_bgb2;

#endif
